config/routes.rb
GlycemicIndex::Application.routes.draw do
  resources :foods

  resources :categories

  root :to => 'categories#listallfoods'
  match '/listallfoods', :to => 'categories#listallfoods'
  get '/about', :to => 'categories#about'

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name
  validates_presence_of :name
  has_many :foods
end

app/models/food.rb
class Food < ActiveRecord::Base
  attr_accessible :category_id, :gi, :name
  validates_presence_of :name
  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  # GET /categories
  # GET /categories.json
  def listallfoods
    @categories = Category.all

    respond_to do |format|
      format.html # listallfoods.html.erb
      format.json { render json: @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])
  # save current category for use when creating food records
    $current_category=params[:id]

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  # GET /foods
  # GET /foods.json
  def index
    @foods = Food.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @foods }
    end
  end

  # GET /foods/1
  # GET /foods/1.json
  def show
    @food = Food.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @food }
    end
  end

  # GET /foods/new
  # GET /foods/new.json
  def new
    @food = Food.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @food }
    end
  end

  # GET /foods/1/edit
  def edit
    @food = Food.find(params[:id])
  end

  # POST /foods
  # POST /foods.json
  def create
    @food = Food.new(params[:food])
  # Attach new food record to current category
    @food.category_id= $current_category
    respond_to do |format|
      if @food.save
        format.html { redirect_to @food, notice: 'Food was successfully created.' }
        format.json { render json: @food, status: :created, location: @food }
      else
        format.html { render action: "new" }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /foods/1
  # PUT /foods/1.json
  def update
    @food = Food.find(params[:id])

    respond_to do |format|
      if @food.update_attributes(params[:food])
        format.html { redirect_to @food, notice: 'Food was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1
  # DELETE /foods/1.json
  def destroy
    @food = Food.find(params[:id])
    @food.destroy

    respond_to do |format|
      format.html { redirect_to foods_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/about.html.erb
<div data-role="header">


<p> Glycemic Index</p>


  <!-- end .header --></div>



<div data-role="content" data-theme="b" data-transition= "flip" >

  <ul data-role="listview" data-filter="true" data-inset="true" data-theme="e">
    <li> <h1>Food Glycemic Index App</h1></li>
    <li> This app enables users to search for Glycemic Index of foods. </li>


 </ul>



  <!-- end .content --></div>

app/views/categories/edit.html.erb
<div data-role="header">

  <h1>Editing category</h1>



  <%= link_to 'Back', categories_path, {"data-icon" =>"back", "class" => "ui-btn-left", "data-theme"=>"b"} %>
  <%= link_to 'Show', @category, {"data-icon" =>"star", "class" => "ui-btn-right", "data-theme"=>"b"} %>
  <!-- end .header --></div>

<div data-role="content" data-theme="a" data-transition= "flip">
  <ul data-role="listview"  data-inset="true">



    <%= render 'form' %>


  </ul>
  <!-- end .content --></div>

app/views/categories/index.html.erb
<div data-role="header">


<p> Food Categories </p>

  <!-- end .header --></div>



<div data-role="content" data-theme="b" data-transition= "flip" >

  <ul data-role="listview" data-filter="true" data-inset="true" data-theme="e">


<% @categories.each do |cat| %>


    <li>
      <%=  link_to  cat.name ,cat %>
      <span class="ui-li-count"> <%=cat.foods.size%> </span>
    </li>



<% end %>
 </ul>


  <!-- end .content --></div>

app/views/categories/listallfoods.html.erb
<div data-role="header">


<p> List all Categories and Foods</p>


  <!-- end .header --></div>



<div data-role="content" data-theme="b" data-transition= "flip" >

  <ul data-role="listview" data-filter="true" data-inset="true" data-theme="e">


<% @categories.each do |cat| %>


    <li>Category:<%= link_to  cat.name ,cat %></li>


        <% cat.foods.order(:gi).each do |fd| %>
            <li>
              <%= link_to fd.name, fd %>
            </li>

        <% end %>

<% end %>
 </ul>


  <!-- end .content --></div>

app/views/categories/new.html.erb
<div data-role="header">

  <h1>New category</h1>


  <%= link_to 'Back', categories_path, {"data-icon" =>"back", "class" => "ui-btn-left", "data-theme"=>"b"} %>
  <!-- end .header --></div>

<div data-role="content" data-theme="a" data-transition= "flip">
  <ul data-role="listview"  data-inset="true">


    <%= render 'form' %>




  </ul>
  <!-- end .content --></div>

app/views/categories/show.html.erb
<div data-role="header">


  <%= link_to 'Back', categories_path, {"data-icon" =>"back", "data-ajax" =>"false", "class" => "ui-btn-left", "data-theme"=>"b"} %>

  <h1> Category:<%= @category.name%> </h1>



  <div data-role="navbar"  data-iconpos="top" >

    <ul>

      <li> <%= link_to 'Add Food', new_food_path, "data-icon"=>"plus", "data-theme"=>"b" %></li>
      <li><%= link_to 'Edit Category',  edit_category_path(@category), {"data-icon" =>"star", "data-theme"=>"b"} %></li>
      <li><%= link_to 'Delete Category ', category_path(@category), method: :delete, data: { confirm: 'Are you sure?' },"data-icon"=>"minus" , "data-theme"=>"b" %> </li>



    </ul>

    <p id="notice"><%= notice %></p>
  </div>

  <!-- end .header --></div>

<div data-role="content" data-theme="e" data-transition= "flip">
  <ul data-role="listview" data-filter="true" data-inset="true">






    <% @category.foods.order(:gi).each do |fd| %>
        <li>
          <%= link_to fd.name, fd %>
        </li>
    <% end %>


  </ul>
  <!-- end .content --></div>

app/views/foods/_form.html.erb
<%= form_for(@food) do |f| %>
  <% if @food.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@food.errors.count, "error") %> prohibited this food from being saved:</h2>

      <ul>
      <% @food.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :gi %><br />
    <%= f.number_field :gi, :min=> 1, :max=>100 %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/foods/edit.html.erb
<div data-role="header">



  <h1> Edit Food</h1>

  <%= link_to 'Back', @food.category, {"data-icon" =>"back", "class" => "ui-btn-left", "data-theme"=>"b"} %>
  <%= link_to 'Show', @food, {"data-icon" =>"star", "class" => "ui-btn-right", "data-theme"=>"b"} %>
  <!-- end .header --></div>

<div data-role="content" data-theme="a" data-transition= "flip">
  <ul data-role="listview" data-inset="true" >




    <%= render 'form' %>

  </ul>
  <!-- end .content --></div>

app/views/foods/index.html.erb
<div data-role="header">

  <p> List Foods  </p>


  <%= link_to 'Back', categories_path, {"data-icon" =>"back", "data-ajax" =>"false", "class" => "ui-btn-right"} %>


  <!-- end .header --></div>



<div data-role="content" data-theme="b" data-transition= "flip" >

  <ul data-role="listview" data-filter="true" data-inset="true" data-theme="e">


      <% @foods.each do |fd| %>

        <li><%= link_to fd.name, fd %></li>


      <% end %>




  </ul>


  <!-- end .content --></div>

app/views/foods/new.html.erb
<div data-role="header">



  <h1> New Food</h1>

  <%= link_to 'Back', @food.category, {"data-icon" =>"back", "class" => "ui-btn-left", "data-theme"=>"b"} %>
  <!-- end .header --></div>

<div data-role="content" data-theme="a" data-transition= "flip">
  <ul data-role="listview"  data-inset="true">



    <%= render 'form' %>

  </ul>
  <!-- end .content --></div>

app/views/foods/show.html.erb
<div data-role="header">



  <h1> Food: <%= @food.name %></h1>


  <%= link_to 'Back', @food.category, {"data-icon" =>"back", "class" => "ui-btn-left", "data-theme"=>"b"} %>
  <%= link_to 'Edit',  edit_food_path(@food), {"data-icon" =>"star", "class" => "ui-btn-right", "data-theme"=>"b"} %>
  <div data-role="navbar"  data-iconpos="top" >

    <ul>
      <li><%= link_to 'List Foods', @food.category, {"data-icon" =>"refresh", "data-theme"=>"b"} %></li>
      <li> <%= link_to 'Add Food', new_food_path, "data-icon"=>"plus", "data-theme"=>"b" %></li>
      <li><%= link_to 'Edit Food',  edit_food_path(@food), {"data-icon" =>"star", "data-theme"=>"b"} %></li>
      <li><%= link_to 'Delete Food', @food, method: :delete, data: { confirm: 'Are you sure?' },"data-icon"=>"minus", "data-theme"=>"b" %></li>

    </ul>

    <p id="notice"><%= notice %></p>

  </div>


  <!-- end .header --></div>

<div data-role="content" data-theme="e" data-transition= "flip">
  <ul  data-inset="true" data-theme="a">

    <p>
      <b>Food:</b>
      <%= @food.name %>
    </p>

    <p>
      <b>Glycemic Index:</b>
      <%= @food.gi %>
    </p>



  </ul>
  <!-- end .content --></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Glycemic Index</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://code.jquery.com/mobile/1.3.0/jquery.mobile-1.3.0.min.css" />
  <script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
  <script src="http://code.jquery.com/mobile/1.3.0/jquery.mobile-1.3.0.min.js"></script>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<body>

<%= image_tag "DigiserveLogo5.png", :width => "65%", :style => 'display: block; margin-left: auto; margin-right: auto;' %>
<%= yield %>


<div data-role="footer">

  <div data-role="navbar" data-position="fixed" data-iconpos="top" >

    <ul>

      <li> <%= link_to 'Add Category', new_category_path, "data-icon"=>"plus", "data-theme"=>"b" %></li>


      <li><%= link_to 'List Category', categories_path, "data-ajax" =>"false", "data-icon"=>"refresh", "data-theme"=>"b" %> </li>

      <li><%= link_to 'List All', listallfoods_path, "data-ajax" =>"false", "data-icon"=>"refresh" , "data-theme"=>"b"%> </li>



      <li><%= link_to 'About', about_path, "data-icon" => "info", "data-theme"=>"b" %></li>



    </ul>

  </div>

  <h4>Digiserve Copyright 2013</h4>
  <!-- end .footer --></div>



</body>
</html>